# Print an optspec for argparse to handle cmd's options that are independent of any subcommand.
function __fish_cldev_global_optspecs
	string join \n v/verbose q/quiet no-color lang= h/help V/version
end

function __fish_cldev_needs_command
	# Figure out if the current invocation already has a command.
	set -l cmd (commandline -opc)
	set -e cmd[1]
	argparse -s (__fish_cldev_global_optspecs) -- $cmd 2>/dev/null
	or return
	if set -q argv[1]
		# Also print the command, so this can be used to figure out what it is.
		echo $argv[1]
		return 1
	end
	return 0
end

function __fish_cldev_using_subcommand
	set -l cmd (__fish_cldev_needs_command)
	test -z "$cmd"
	and return 1
	contains -- $cmd[1] $argv
end

complete -c cldev -n "__fish_cldev_needs_command" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_needs_command" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_needs_command" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_needs_command" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_needs_command" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_needs_command" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_needs_command" -f -a "config" -d 'Configuration management commands'
complete -c cldev -n "__fish_cldev_needs_command" -f -a "dev" -d 'Development workflow commands'
complete -c cldev -n "__fish_cldev_needs_command" -f -a "git" -d 'Git operation commands'
complete -c cldev -n "__fish_cldev_needs_command" -f -a "quality" -d 'Code quality commands'
complete -c cldev -n "__fish_cldev_needs_command" -f -a "tech" -d 'Tech stack specific commands'
complete -c cldev -n "__fish_cldev_needs_command" -f -a "ops" -d 'Operations commands'
complete -c cldev -n "__fish_cldev_needs_command" -f -a "analysis" -d 'Analysis and review commands'
complete -c cldev -n "__fish_cldev_needs_command" -f -a "lr" -d 'Learning record commands'
complete -c cldev -n "__fish_cldev_needs_command" -f -a "todo" -d 'Todo management commands'
complete -c cldev -n "__fish_cldev_needs_command" -f -a "completions" -d 'Generate shell completions'
complete -c cldev -n "__fish_cldev_needs_command" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c cldev -n "__fish_cldev_using_subcommand config; and not __fish_seen_subcommand_from init check edit list maintain update-docs help" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand config; and not __fish_seen_subcommand_from init check edit list maintain update-docs help" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand config; and not __fish_seen_subcommand_from init check edit list maintain update-docs help" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand config; and not __fish_seen_subcommand_from init check edit list maintain update-docs help" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand config; and not __fish_seen_subcommand_from init check edit list maintain update-docs help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand config; and not __fish_seen_subcommand_from init check edit list maintain update-docs help" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand config; and not __fish_seen_subcommand_from init check edit list maintain update-docs help" -f -a "init" -d 'Initialize cldev configuration'
complete -c cldev -n "__fish_cldev_using_subcommand config; and not __fish_seen_subcommand_from init check edit list maintain update-docs help" -f -a "check" -d 'Check configuration health'
complete -c cldev -n "__fish_cldev_using_subcommand config; and not __fish_seen_subcommand_from init check edit list maintain update-docs help" -f -a "edit" -d 'Edit configuration file'
complete -c cldev -n "__fish_cldev_using_subcommand config; and not __fish_seen_subcommand_from init check edit list maintain update-docs help" -f -a "list" -d 'List all configurations'
complete -c cldev -n "__fish_cldev_using_subcommand config; and not __fish_seen_subcommand_from init check edit list maintain update-docs help" -f -a "maintain" -d 'Maintain configuration files'
complete -c cldev -n "__fish_cldev_using_subcommand config; and not __fish_seen_subcommand_from init check edit list maintain update-docs help" -f -a "update-docs" -d 'Update documentation'
complete -c cldev -n "__fish_cldev_using_subcommand config; and not __fish_seen_subcommand_from init check edit list maintain update-docs help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from init" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from init" -s d -l defaults -d 'Skip interactive prompts and use defaults'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from init" -s f -l force -d 'Force initialization even if config exists'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from init" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from init" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from init" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from init" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from init" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from check" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from check" -s d -l detailed -d 'Perform detailed validation'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from check" -s f -l fix -d 'Fix issues automatically if possible'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from check" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from check" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from check" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from check" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from check" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from edit" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from edit" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from edit" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from edit" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from edit" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from edit" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from list" -s f -l filter -d 'Filter by configuration type' -r -f -a "global\t''
project\t''
stack\t''"
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from list" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from list" -s d -l detailed -d 'Show detailed information'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from list" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from list" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from list" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from list" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from maintain" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from maintain" -s b -l backup -d 'Backup configurations before maintenance'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from maintain" -s c -l cleanup -d 'Clean up old backups'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from maintain" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from maintain" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from maintain" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from maintain" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from maintain" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from update-docs" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from update-docs" -l validate -d 'Validate documentation after update'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from update-docs" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from update-docs" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from update-docs" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from update-docs" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from update-docs" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "init" -d 'Initialize cldev configuration'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "check" -d 'Check configuration health'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "edit" -d 'Edit configuration file'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "list" -d 'List all configurations'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "maintain" -d 'Maintain configuration files'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "update-docs" -d 'Update documentation'
complete -c cldev -n "__fish_cldev_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and not __fish_seen_subcommand_from urgent fix debug feature refactor optimize research help" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand dev; and not __fish_seen_subcommand_from urgent fix debug feature refactor optimize research help" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and not __fish_seen_subcommand_from urgent fix debug feature refactor optimize research help" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and not __fish_seen_subcommand_from urgent fix debug feature refactor optimize research help" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and not __fish_seen_subcommand_from urgent fix debug feature refactor optimize research help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and not __fish_seen_subcommand_from urgent fix debug feature refactor optimize research help" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and not __fish_seen_subcommand_from urgent fix debug feature refactor optimize research help" -f -a "urgent" -d 'Emergency response for production issues (5min initial response)'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and not __fish_seen_subcommand_from urgent fix debug feature refactor optimize research help" -f -a "fix" -d 'Fix critical bugs (same-day resolution target)'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and not __fish_seen_subcommand_from urgent fix debug feature refactor optimize research help" -f -a "debug" -d 'Systematic debugging workflow'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and not __fish_seen_subcommand_from urgent fix debug feature refactor optimize research help" -f -a "feature" -d 'Implement new feature (requirements to test)'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and not __fish_seen_subcommand_from urgent fix debug feature refactor optimize research help" -f -a "refactor" -d 'Safe refactoring (incremental execution)'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and not __fish_seen_subcommand_from urgent fix debug feature refactor optimize research help" -f -a "optimize" -d 'Performance optimization (measure -> analyze -> improve)'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and not __fish_seen_subcommand_from urgent fix debug feature refactor optimize research help" -f -a "research" -d 'Technical research and learning records'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and not __fish_seen_subcommand_from urgent fix debug feature refactor optimize research help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from urgent" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from urgent" -s y -l yes -d 'Skip confirmation prompts'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from urgent" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from urgent" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from urgent" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from urgent" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from urgent" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from fix" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from fix" -s b -l branch -d 'Create fix branch automatically'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from fix" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from fix" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from fix" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from fix" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from fix" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from debug" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from debug" -s v -l verbose -d 'Enable verbose debugging output'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from debug" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from debug" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from debug" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from debug" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from feature" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from feature" -s s -l skip-confirm -d 'Skip requirements confirmation'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from feature" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from feature" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from feature" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from feature" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from feature" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from refactor" -s s -l scope -d 'Refactoring scope' -r -f -a "function\t''
module\t''
package\t''"
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from refactor" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from refactor" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from refactor" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from refactor" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from refactor" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from refactor" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from optimize" -s f -l focus -d 'Focus area for optimization' -r -f -a "performance\t''
memory\t''
bundle\t''
database\t''"
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from optimize" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from optimize" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from optimize" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from optimize" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from optimize" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from optimize" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from research" -s f -l format -d 'Output format' -r -f -a "markdown\t''
json\t''
html\t''"
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from research" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from research" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from research" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from research" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from research" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from research" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from help" -f -a "urgent" -d 'Emergency response for production issues (5min initial response)'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from help" -f -a "fix" -d 'Fix critical bugs (same-day resolution target)'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from help" -f -a "debug" -d 'Systematic debugging workflow'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from help" -f -a "feature" -d 'Implement new feature (requirements to test)'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from help" -f -a "refactor" -d 'Safe refactoring (incremental execution)'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from help" -f -a "optimize" -d 'Performance optimization (measure -> analyze -> improve)'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from help" -f -a "research" -d 'Technical research and learning records'
complete -c cldev -n "__fish_cldev_using_subcommand dev; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c cldev -n "__fish_cldev_using_subcommand git; and not __fish_seen_subcommand_from commit branch merge-request status help" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand git; and not __fish_seen_subcommand_from commit branch merge-request status help" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand git; and not __fish_seen_subcommand_from commit branch merge-request status help" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand git; and not __fish_seen_subcommand_from commit branch merge-request status help" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand git; and not __fish_seen_subcommand_from commit branch merge-request status help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand git; and not __fish_seen_subcommand_from commit branch merge-request status help" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand git; and not __fish_seen_subcommand_from commit branch merge-request status help" -f -a "commit" -d 'Create conventional commit'
complete -c cldev -n "__fish_cldev_using_subcommand git; and not __fish_seen_subcommand_from commit branch merge-request status help" -f -a "branch" -d 'Create conventional branch'
complete -c cldev -n "__fish_cldev_using_subcommand git; and not __fish_seen_subcommand_from commit branch merge-request status help" -f -a "merge-request" -d 'Create merge request (GitLab) or pull request (GitHub)'
complete -c cldev -n "__fish_cldev_using_subcommand git; and not __fish_seen_subcommand_from commit branch merge-request status help" -f -a "status" -d 'Show enhanced git status'
complete -c cldev -n "__fish_cldev_using_subcommand git; and not __fish_seen_subcommand_from commit branch merge-request status help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from commit" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from commit" -l no-verify -d 'Skip pre-commit hooks'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from commit" -l amend -d 'Amend previous commit'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from commit" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from commit" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from commit" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from commit" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from commit" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from branch" -s b -l branch-type -d 'Branch type' -r -f -a "feature\t''
fix\t''
hotfix\t''
refactor\t''
docs\t''
test\t''"
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from branch" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from branch" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from branch" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from branch" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from branch" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from branch" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from merge-request" -s t -l target -d 'Target branch' -r
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from merge-request" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from merge-request" -s d -l detailed -d 'Enable detailed mode'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from merge-request" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from merge-request" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from merge-request" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from merge-request" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from merge-request" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from status" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from status" -s d -l detailed -d 'Show detailed branch information'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from status" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from status" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from status" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from status" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from help" -f -a "commit" -d 'Create conventional commit'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from help" -f -a "branch" -d 'Create conventional branch'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from help" -f -a "merge-request" -d 'Create merge request (GitLab) or pull request (GitHub)'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from help" -f -a "status" -d 'Show enhanced git status'
complete -c cldev -n "__fish_cldev_using_subcommand git; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and not __fish_seen_subcommand_from lint format test help" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand quality; and not __fish_seen_subcommand_from lint format test help" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and not __fish_seen_subcommand_from lint format test help" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and not __fish_seen_subcommand_from lint format test help" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and not __fish_seen_subcommand_from lint format test help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and not __fish_seen_subcommand_from lint format test help" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and not __fish_seen_subcommand_from lint format test help" -f -a "lint" -d 'Run linter'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and not __fish_seen_subcommand_from lint format test help" -f -a "format" -d 'Format code'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and not __fish_seen_subcommand_from lint format test help" -f -a "test" -d 'Run tests'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and not __fish_seen_subcommand_from lint format test help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from lint" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from lint" -s f -l fix -d 'Auto-fix issues'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from lint" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from lint" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from lint" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from lint" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from lint" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from format" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from format" -s c -l check -d 'Check formatting without modifying files'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from format" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from format" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from format" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from format" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from format" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from test" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from test" -s c -l coverage -d 'Generate coverage report'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from test" -s w -l watch -d 'Watch mode'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from test" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from test" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from test" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from test" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from test" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from help" -f -a "lint" -d 'Run linter'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from help" -f -a "format" -d 'Format code'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from help" -f -a "test" -d 'Run tests'
complete -c cldev -n "__fish_cldev_using_subcommand quality; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c cldev -n "__fish_cldev_using_subcommand tech; and not __fish_seen_subcommand_from start help" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand tech; and not __fish_seen_subcommand_from start help" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand tech; and not __fish_seen_subcommand_from start help" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand tech; and not __fish_seen_subcommand_from start help" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand tech; and not __fish_seen_subcommand_from start help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand tech; and not __fish_seen_subcommand_from start help" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand tech; and not __fish_seen_subcommand_from start help" -f -a "start" -d 'Start development environment'
complete -c cldev -n "__fish_cldev_using_subcommand tech; and not __fish_seen_subcommand_from start help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c cldev -n "__fish_cldev_using_subcommand tech; and __fish_seen_subcommand_from start" -s p -l port -d 'Port number' -r
complete -c cldev -n "__fish_cldev_using_subcommand tech; and __fish_seen_subcommand_from start" -s e -l env -d 'Environment (development/production)' -r -f -a "development\t''
staging\t''
production\t''"
complete -c cldev -n "__fish_cldev_using_subcommand tech; and __fish_seen_subcommand_from start" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand tech; and __fish_seen_subcommand_from start" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand tech; and __fish_seen_subcommand_from start" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand tech; and __fish_seen_subcommand_from start" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand tech; and __fish_seen_subcommand_from start" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand tech; and __fish_seen_subcommand_from start" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand tech; and __fish_seen_subcommand_from help" -f -a "start" -d 'Start development environment'
complete -c cldev -n "__fish_cldev_using_subcommand tech; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c cldev -n "__fish_cldev_using_subcommand ops; and not __fish_seen_subcommand_from build deploy help" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand ops; and not __fish_seen_subcommand_from build deploy help" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand ops; and not __fish_seen_subcommand_from build deploy help" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand ops; and not __fish_seen_subcommand_from build deploy help" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand ops; and not __fish_seen_subcommand_from build deploy help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand ops; and not __fish_seen_subcommand_from build deploy help" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand ops; and not __fish_seen_subcommand_from build deploy help" -f -a "build" -d 'Build project'
complete -c cldev -n "__fish_cldev_using_subcommand ops; and not __fish_seen_subcommand_from build deploy help" -f -a "deploy" -d 'Deploy project'
complete -c cldev -n "__fish_cldev_using_subcommand ops; and not __fish_seen_subcommand_from build deploy help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c cldev -n "__fish_cldev_using_subcommand ops; and __fish_seen_subcommand_from build" -s e -l env -d 'Build environment' -r -f -a "development\t''
staging\t''
production\t''"
complete -c cldev -n "__fish_cldev_using_subcommand ops; and __fish_seen_subcommand_from build" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand ops; and __fish_seen_subcommand_from build" -s a -l analyze -d 'Analyze bundle after build'
complete -c cldev -n "__fish_cldev_using_subcommand ops; and __fish_seen_subcommand_from build" -s c -l clean -d 'Clean before build'
complete -c cldev -n "__fish_cldev_using_subcommand ops; and __fish_seen_subcommand_from build" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand ops; and __fish_seen_subcommand_from build" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand ops; and __fish_seen_subcommand_from build" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand ops; and __fish_seen_subcommand_from build" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand ops; and __fish_seen_subcommand_from build" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand ops; and __fish_seen_subcommand_from deploy" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand ops; and __fish_seen_subcommand_from deploy" -s y -l yes -d 'Skip confirmation prompts'
complete -c cldev -n "__fish_cldev_using_subcommand ops; and __fish_seen_subcommand_from deploy" -s d -l dry-run -d 'Dry run (show what would be deployed)'
complete -c cldev -n "__fish_cldev_using_subcommand ops; and __fish_seen_subcommand_from deploy" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand ops; and __fish_seen_subcommand_from deploy" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand ops; and __fish_seen_subcommand_from deploy" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand ops; and __fish_seen_subcommand_from deploy" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand ops; and __fish_seen_subcommand_from deploy" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand ops; and __fish_seen_subcommand_from help" -f -a "build" -d 'Build project'
complete -c cldev -n "__fish_cldev_using_subcommand ops; and __fish_seen_subcommand_from help" -f -a "deploy" -d 'Deploy project'
complete -c cldev -n "__fish_cldev_using_subcommand ops; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and not __fish_seen_subcommand_from analyze explain review-mr serena help" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and not __fish_seen_subcommand_from analyze explain review-mr serena help" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and not __fish_seen_subcommand_from analyze explain review-mr serena help" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and not __fish_seen_subcommand_from analyze explain review-mr serena help" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and not __fish_seen_subcommand_from analyze explain review-mr serena help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and not __fish_seen_subcommand_from analyze explain review-mr serena help" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and not __fish_seen_subcommand_from analyze explain review-mr serena help" -f -a "analyze" -d 'Analyze project'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and not __fish_seen_subcommand_from analyze explain review-mr serena help" -f -a "explain" -d 'Explain code or concept'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and not __fish_seen_subcommand_from analyze explain review-mr serena help" -f -a "review-mr" -d 'Review merge request'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and not __fish_seen_subcommand_from analyze explain review-mr serena help" -f -a "serena" -d 'Semantic code analysis (Serena MCP)'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and not __fish_seen_subcommand_from analyze explain review-mr serena help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from analyze" -s f -l format -d 'Output format' -r -f -a "text\t''
json\t''
html\t''"
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from analyze" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from analyze" -s d -l detailed -d 'Enable detailed analysis'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from analyze" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from analyze" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from analyze" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from analyze" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from analyze" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from explain" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from explain" -s e -l examples -d 'Show usage examples'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from explain" -s d -l detailed -d 'Detailed explanation'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from explain" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from explain" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from explain" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from explain" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from explain" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from review-mr" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from review-mr" -s d -l detailed -d 'Enable detailed review'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from review-mr" -l security-focus -d 'Focus on security'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from review-mr" -l performance-focus -d 'Focus on performance'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from review-mr" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from review-mr" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from review-mr" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from review-mr" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from review-mr" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from serena" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from serena" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from serena" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from serena" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from serena" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from serena" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from help" -f -a "analyze" -d 'Analyze project'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from help" -f -a "explain" -d 'Explain code or concept'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from help" -f -a "review-mr" -d 'Review merge request'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from help" -f -a "serena" -d 'Semantic code analysis (Serena MCP)'
complete -c cldev -n "__fish_cldev_using_subcommand analysis; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and not __fish_seen_subcommand_from find stats problems new help" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand lr; and not __fish_seen_subcommand_from find stats problems new help" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and not __fish_seen_subcommand_from find stats problems new help" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and not __fish_seen_subcommand_from find stats problems new help" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and not __fish_seen_subcommand_from find stats problems new help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and not __fish_seen_subcommand_from find stats problems new help" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and not __fish_seen_subcommand_from find stats problems new help" -f -a "find" -d 'Find learning records'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and not __fish_seen_subcommand_from find stats problems new help" -f -a "stats" -d 'Show learning statistics'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and not __fish_seen_subcommand_from find stats problems new help" -f -a "problems" -d 'List unsolved problems'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and not __fish_seen_subcommand_from find stats problems new help" -f -a "new" -d 'Create new learning record'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and not __fish_seen_subcommand_from find stats problems new help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from find" -s f -l field -d 'Search in specific field' -r -f -a "topic\t''
tag\t''
content\t''"
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from find" -s l -l limit -d 'Limit results' -r
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from find" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from find" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from find" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from find" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from find" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from find" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from stats" -s p -l period -d 'Time period for statistics' -r -f -a "day\t''
week\t''
month\t''
year\t''"
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from stats" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from stats" -s d -l detailed -d 'Show detailed breakdown'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from stats" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from stats" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from stats" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from stats" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from stats" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from problems" -s p -l priority -d 'Priority filter' -r -f -a "low\t''
medium\t''
high\t''
critical\t''"
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from problems" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from problems" -s r -l recent -d 'Show only recent problems'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from problems" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from problems" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from problems" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from problems" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from problems" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from new" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from new" -s e -l edit -d 'Open editor immediately'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from new" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from new" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from new" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from new" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from new" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from help" -f -a "find" -d 'Find learning records'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from help" -f -a "stats" -d 'Show learning statistics'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from help" -f -a "problems" -d 'List unsolved problems'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from help" -f -a "new" -d 'Create new learning record'
complete -c cldev -n "__fish_cldev_using_subcommand lr; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c cldev -n "__fish_cldev_using_subcommand todo; and not __fish_seen_subcommand_from manage help" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand todo; and not __fish_seen_subcommand_from manage help" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand todo; and not __fish_seen_subcommand_from manage help" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand todo; and not __fish_seen_subcommand_from manage help" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand todo; and not __fish_seen_subcommand_from manage help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand todo; and not __fish_seen_subcommand_from manage help" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand todo; and not __fish_seen_subcommand_from manage help" -f -a "manage" -d 'Manage todos'
complete -c cldev -n "__fish_cldev_using_subcommand todo; and not __fish_seen_subcommand_from manage help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c cldev -n "__fish_cldev_using_subcommand todo; and __fish_seen_subcommand_from manage" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand todo; and __fish_seen_subcommand_from manage" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand todo; and __fish_seen_subcommand_from manage" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand todo; and __fish_seen_subcommand_from manage" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand todo; and __fish_seen_subcommand_from manage" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand todo; and __fish_seen_subcommand_from manage" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand todo; and __fish_seen_subcommand_from help" -f -a "manage" -d 'Manage todos'
complete -c cldev -n "__fish_cldev_using_subcommand todo; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c cldev -n "__fish_cldev_using_subcommand completions" -l lang -d 'Set language (ja/en)' -r -f -a "en\t'English'
ja\t'Japanese'"
complete -c cldev -n "__fish_cldev_using_subcommand completions" -s i -l install -d 'Print installation instructions'
complete -c cldev -n "__fish_cldev_using_subcommand completions" -s v -l verbose -d 'Enable verbose output'
complete -c cldev -n "__fish_cldev_using_subcommand completions" -s q -l quiet -d 'Suppress non-error output'
complete -c cldev -n "__fish_cldev_using_subcommand completions" -l no-color -d 'Disable colored output'
complete -c cldev -n "__fish_cldev_using_subcommand completions" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c cldev -n "__fish_cldev_using_subcommand completions" -s V -l version -d 'Print version'
complete -c cldev -n "__fish_cldev_using_subcommand help; and not __fish_seen_subcommand_from config dev git quality tech ops analysis lr todo completions help" -f -a "config" -d 'Configuration management commands'
complete -c cldev -n "__fish_cldev_using_subcommand help; and not __fish_seen_subcommand_from config dev git quality tech ops analysis lr todo completions help" -f -a "dev" -d 'Development workflow commands'
complete -c cldev -n "__fish_cldev_using_subcommand help; and not __fish_seen_subcommand_from config dev git quality tech ops analysis lr todo completions help" -f -a "git" -d 'Git operation commands'
complete -c cldev -n "__fish_cldev_using_subcommand help; and not __fish_seen_subcommand_from config dev git quality tech ops analysis lr todo completions help" -f -a "quality" -d 'Code quality commands'
complete -c cldev -n "__fish_cldev_using_subcommand help; and not __fish_seen_subcommand_from config dev git quality tech ops analysis lr todo completions help" -f -a "tech" -d 'Tech stack specific commands'
complete -c cldev -n "__fish_cldev_using_subcommand help; and not __fish_seen_subcommand_from config dev git quality tech ops analysis lr todo completions help" -f -a "ops" -d 'Operations commands'
complete -c cldev -n "__fish_cldev_using_subcommand help; and not __fish_seen_subcommand_from config dev git quality tech ops analysis lr todo completions help" -f -a "analysis" -d 'Analysis and review commands'
complete -c cldev -n "__fish_cldev_using_subcommand help; and not __fish_seen_subcommand_from config dev git quality tech ops analysis lr todo completions help" -f -a "lr" -d 'Learning record commands'
complete -c cldev -n "__fish_cldev_using_subcommand help; and not __fish_seen_subcommand_from config dev git quality tech ops analysis lr todo completions help" -f -a "todo" -d 'Todo management commands'
complete -c cldev -n "__fish_cldev_using_subcommand help; and not __fish_seen_subcommand_from config dev git quality tech ops analysis lr todo completions help" -f -a "completions" -d 'Generate shell completions'
complete -c cldev -n "__fish_cldev_using_subcommand help; and not __fish_seen_subcommand_from config dev git quality tech ops analysis lr todo completions help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from config" -f -a "init" -d 'Initialize cldev configuration'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from config" -f -a "check" -d 'Check configuration health'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from config" -f -a "edit" -d 'Edit configuration file'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from config" -f -a "list" -d 'List all configurations'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from config" -f -a "maintain" -d 'Maintain configuration files'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from config" -f -a "update-docs" -d 'Update documentation'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from dev" -f -a "urgent" -d 'Emergency response for production issues (5min initial response)'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from dev" -f -a "fix" -d 'Fix critical bugs (same-day resolution target)'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from dev" -f -a "debug" -d 'Systematic debugging workflow'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from dev" -f -a "feature" -d 'Implement new feature (requirements to test)'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from dev" -f -a "refactor" -d 'Safe refactoring (incremental execution)'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from dev" -f -a "optimize" -d 'Performance optimization (measure -> analyze -> improve)'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from dev" -f -a "research" -d 'Technical research and learning records'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from git" -f -a "commit" -d 'Create conventional commit'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from git" -f -a "branch" -d 'Create conventional branch'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from git" -f -a "merge-request" -d 'Create merge request (GitLab) or pull request (GitHub)'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from git" -f -a "status" -d 'Show enhanced git status'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from quality" -f -a "lint" -d 'Run linter'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from quality" -f -a "format" -d 'Format code'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from quality" -f -a "test" -d 'Run tests'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from tech" -f -a "start" -d 'Start development environment'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from ops" -f -a "build" -d 'Build project'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from ops" -f -a "deploy" -d 'Deploy project'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from analysis" -f -a "analyze" -d 'Analyze project'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from analysis" -f -a "explain" -d 'Explain code or concept'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from analysis" -f -a "review-mr" -d 'Review merge request'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from analysis" -f -a "serena" -d 'Semantic code analysis (Serena MCP)'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from lr" -f -a "find" -d 'Find learning records'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from lr" -f -a "stats" -d 'Show learning statistics'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from lr" -f -a "problems" -d 'List unsolved problems'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from lr" -f -a "new" -d 'Create new learning record'
complete -c cldev -n "__fish_cldev_using_subcommand help; and __fish_seen_subcommand_from todo" -f -a "manage" -d 'Manage todos'
